#!/usr/bin/env python3

import rclpy
from rclpy.clock import Clock, ClockType
import numpy as np

import rclpy.time

class PID_controller(object):
    def __init__(self, kp, ki, kd):
        self.kp = kp
        self.ki = ki #적분 관련
        self.kd = kd #미분 관련

        self.desired_roll_pitch = np.array([0.0, 0.0]) #목표 롤 피치
        self.desired_rpy = np.array([0.0, 0.0, 0.0]) #목표 rpy

        # TODO : Tune max_I
        self.max_I = 0.2 #적분 범위 설정정
        self.last_error = np.array([0.0,0.0]) #이전 오차

        self.clock = Clock(clock_type=ClockType.ROS_TIME)
        

    def reset(self):
        self.last_time = self.clock.now() #지금 시간 
        self.I_term = np.array([0.0,0.0]) #적분
        self.D_term = np.array([0.0,0.0]) #미분
        self.last_error = np.array([0.0,0.0]) #이전 오차
    
    def run(self, roll, pitch):
        error = self.desired_roll_pitch - np.array([roll, pitch]) #오차

        t_now = self.clock.now() #현재 시간
        step, step_millis = (t_now - self.last_time).seconds_nanoseconds() #단게의 시간

        step = step+step_millis

        self.I_term = self.I_term + error*step #적분
        
        for i in range(2): #적분값 범위 설정
            if(self.I_term[i] < -self.max_I):
                self.I_term[i] = -self.max_I
            elif(self.I_term[i] > self.max_I):
                self.I_term[i] = self.max_I
        
        self.D_term = (error - self.last_error) / step #미분 오차를 단계에 따라 나눈 무언가

        self.last_time = t_now #현재값을 이전값으로 변경함
        self.last_error = error #현재값을 이전값으로 변경함

        P_ret = self.kp * error 
        I_ret = self.ki * error #적분 관련 오차
        D_ret = self.kd * error #미분 관련 오차

        return P_ret+I_ret+D_ret #오차 총합
    
    # def run_rpy(self, roll, pitch, yaw)

    def desired_RP_angles(des_roll, des_pitch):
        self.desired_roll_pitch = np.array([des_roll, des_pitch]) #목표 롤 피치
